import { chmod, readFile } from "node:fs/promises";
import { resolve } from "node:path";

import { ValidationError } from "../../core/errors.js";
import { ensureWritable } from "../../core/guards.js";
import {
    inspectManagedFile,
    renderManagedBlock,
    syncManagedFile
} from "../generated/managed-files.js";

const PACKAGE_VERSION = JSON.parse(
    await readFile(new URL("../../../../package.json", import.meta.url), "utf8")
).version;

export const CI_TARGETS = Object.freeze({
    github: {
        path: ".github/workflows/workfile.yml",
        kind: "ci-github",
        mode: "dedicated"
    },
    gitlab: {
        path: ".gitlab/workfile.yml",
        kind: "ci-gitlab",
        mode: "dedicated"
    },
    generic: {
        path: ".project/ci/workfile.sh",
        kind: "ci-generic",
        mode: "dedicated"
    }
});

function githubBody(workspace) {
    const node = String(workspace.config.ci.nodeVersion || "22");
    return `# Generated by @illodev/workfile ${PACKAGE_VERSION}
name: Workfile

on:
  pull_request:
  push:
    branches: [main, master, dev]

permissions:
  contents: read

jobs:
  doctor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "${node}"
      - name: Validate repository protocol
        run: npx --yes @illodev/workfile@${PACKAGE_VERSION} doctor --json
      - name: Check generated agent instructions
        run: npx --yes @illodev/workfile@${PACKAGE_VERSION} agents check --json
`;
}

function gitlabBody(workspace) {
    const node = String(workspace.config.ci.nodeVersion || "22");
    return `# Generated by @illodev/workfile ${PACKAGE_VERSION}
project_protocol:
  image: node:${node}-slim
  stage: test
  script:
    - npx --yes @illodev/workfile@${PACKAGE_VERSION} doctor --json
    - npx --yes @illodev/workfile@${PACKAGE_VERSION} agents check --json
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH
`;
}

function genericBody() {
    return `#!/usr/bin/env sh
set -eu

npx --yes @illodev/workfile@${PACKAGE_VERSION} doctor --json
npx --yes @illodev/workfile@${PACKAGE_VERSION} agents check --json
`;
}

function targetBody(workspace, id) {
    if (id === "github") return githubBody(workspace);
    if (id === "gitlab") return gitlabBody(workspace);
    if (id === "generic") return genericBody();
    throw new ValidationError(
        "CI_TARGET_UNSUPPORTED",
        `Unsupported CI target: ${id}`,
        { target: id, supported: Object.keys(CI_TARGETS) }
    );
}

export function renderCiFiles(workspace, options: any = {}) {
    const targets = options.targets || workspace.config.ci.targets;
    return targets.map((id) => {
        const definition = CI_TARGETS[id];
        if (!definition) {
            throw new ValidationError(
                "CI_TARGET_UNSUPPORTED",
                `Unsupported CI target: ${id}`,
                { target: id, supported: Object.keys(CI_TARGETS) }
            );
        }
        return {
            id,
            path: resolve(workspace.root, definition.path),
            label: definition.path,
            requireMarker: true,
            block: renderManagedBlock({
                kind: definition.kind,
                version: PACKAGE_VERSION,
                body: targetBody(workspace, id),
                style: "hash"
            })
        };
    });
}

export async function syncCiTemplates(workspace, options: any = {}) {
    if (!options.dryRun) ensureWritable(workspace);
    const files = renderCiFiles(workspace, options);
    const results = [];
    for (const file of files) {
        const result = await syncManagedFile({
            ...file,
            force: Boolean(options.force),
            dryRun: Boolean(options.dryRun)
        });
        if (!options.dryRun && file.id === "generic") {
            await chmod(file.path, 0o755);
        }
        results.push(result);
    }
    return {
        version: PACKAGE_VERSION,
        targets: options.targets || workspace.config.ci.targets,
        changed: results.filter((item) => item.status !== "unchanged").length,
        files: results
    };
}

export async function checkCiTemplates(workspace, options: any = {}) {
    const files = renderCiFiles(workspace, options);
    const results = [];
    for (const file of files) {
        results.push(
            await inspectManagedFile({
                path: file.path,
                block: file.block,
                label: file.label
            })
        );
    }
    const issues = results
        .filter((item) => item.status !== "current")
        .map((item) => ({
            severity: "warning",
            code:
                item.status === "missing"
                    ? "ci-template-missing"
                    : item.status === "unmanaged"
                      ? "ci-template-unmanaged"
                      : "ci-template-stale",
            file: item.path,
            message:
                item.status === "missing"
                    ? `Generated CI template is missing: ${item.path}`
                    : item.status === "unmanaged"
                      ? `Generated CI template has no managed block: ${item.path}`
                      : `Generated CI template is stale: ${item.path}`,
            details: item
        }));
    return {
        ok: issues.length === 0,
        version: PACKAGE_VERSION,
        counts: {
            current: results.filter((item) => item.status === "current").length,
            stale: results.filter((item) => item.status === "stale").length,
            missing: results.filter((item) => item.status === "missing").length,
            unmanaged: results.filter((item) => item.status === "unmanaged").length
        },
        files: results,
        issues
    };
}
