import { chmod, readFile } from "node:fs/promises";
import { resolve } from "node:path";

import { ValidationError } from "../../core/errors.js";
import { ensureWritable } from "../../core/guards.js";
import {
    inspectManagedFile,
    type ManagedFileReport,
    renderManagedBlock,
    syncManagedFile
} from "../generated/managed-files.js";

const PACKAGE_VERSION = JSON.parse(
    await readFile(new URL("../../../../package.json", import.meta.url), "utf8")
).version;

export const CI_TARGETS = Object.freeze({
    github: {
        path: ".github/workflows/workfile.yml",
        kind: "ci-github",
        mode: "dedicated"
    },
    gitlab: {
        path: ".gitlab/workfile.yml",
        kind: "ci-gitlab",
        mode: "dedicated"
    },
    generic: {
        path: ".project/ci/workfile.sh",
        kind: "ci-generic",
        mode: "dedicated"
    }
});

/**
 * The job runs the checkout's own code, and the template says so.
 *
 * Every command below loads the workspace, and loading a workspace `import()`s
 * `project.config.mjs` out of the checkout — so on a pull request this job
 * executes code the pull request wrote, before it reads a single card. Two hops:
 * `doctor` then calls every `healthCheck` that module declared. That is the
 * ordinary cost of building a pull request rather than a defect, and it is why
 * the useful controls here are about what the job *holds* rather than about what
 * it runs. The three targets differ sharply on that, and each says what it can
 * enforce and what it cannot.
 *
 * Each generated file states both hops, because a reader who only knows the
 * first will price this wrongly: "it imports a config file" sounds like reading
 * settings, and it is not. See ADR-0019 and LRN-0028.
 */
const EXECUTES_REPOSITORY_CODE = [
    "Both commands load the workspace, which `import()`s project.config.mjs from",
    "the checkout: this job runs that file's module body, and `doctor` then calls",
    "every healthCheck and search provider it declares. On a pull request that is",
    "code the pull request wrote. Nothing in Workfile sandboxes it — containment",
    "is whatever this job holds, described below."
];

function executesRepositoryCode() {
    return EXECUTES_REPOSITORY_CODE.map((line) => `# ${line}`).join("\n");
}

/**
 * Why the card runner and the write token are in different jobs.
 *
 * T-0189. A card may bind a criterion to a command, and running that command is
 * the only thing that can check it. So one job here executes commands a pull
 * request declared, and it must therefore hold nothing at all — `permissions:
 * {}`, no credentials left in `.git/config`, no secrets a fork could reach.
 *
 * But the evidence has to be written back, and writing to the repository needs
 * `contents: write`. Putting that scope on the job that runs card commands would
 * hand a token to a process a pull request configured, which is the whole thing
 * ADR-0019 exists to say out loud. So the run and the write are two jobs: the
 * first produces a patch bounded to the protocol directory, the second applies
 * it and holds no repository code at all — it never invokes Workfile, because
 * every Workfile command `import()`s `project.config.mjs` from the checkout.
 *
 * On a fork the second job cannot write whatever this file says: GitHub issues a
 * read-only token for `pull_request` from a fork, so the push fails and nothing
 * is recorded. That is a fail-closed enforced by the platform rather than by our
 * condition, and the condition below is documentation of it.
 */
const TWO_JOB_SPLIT = [
    "The job that runs card-declared commands holds nothing, and the job that",
    "holds a write token runs no repository code. They cannot be one job: a",
    "criterion bound to a command can only be checked by running it, and a",
    "process a pull request configured must not be handed a token. See T-0189.",
    "On a fork the write token is read-only whatever this file says, so nothing",
    "is recorded there — GitHub enforces that, not the condition below."
];

function twoJobSplit(indent = "# ") {
    return TWO_JOB_SPLIT.map((line) => `${indent}${line}`).join("\n");
}

function githubBody(workspace) {
    const node = String(workspace.config.ci.nodeVersion || "22");
    const protocolRoot = String(workspace.config.storage.root || ".project")
        .replace(/\\/g, "/")
        .replace(/^\.\//, "")
        .replace(/\/+$/, "");
    return `# Generated by @illodev/workfile ${PACKAGE_VERSION}
#
${executesRepositoryCode()}
name: Workfile

on:
  pull_request:
  push:
    branches: [main, master, dev]

# Nothing at the top level, so a job added by hand starts from no permissions
# rather than inheriting these. This job runs code from the checkout, including
# a fork's on \`pull_request\`; what protects the repository there is GitHub
# withholding secrets from a fork, not the scope below.
permissions: {}

jobs:
  doctor:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          # Otherwise the token is left in .git/config as an http.extraheader,
          # where any later step can read it. Nothing here pushes.
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: "${node}"
      - name: Validate repository protocol
        run: npx --yes @illodev/workfile@${PACKAGE_VERSION} doctor --json
      - name: Check generated agent instructions
        run: npx --yes @illodev/workfile@${PACKAGE_VERSION} agents check --json

${twoJobSplit("  # ")}
  cards:
    # Only on a pull request. "The cards this branch touched" is a diff against a
    # base, and a push to a default branch has none — running here would answer
    # for whatever ref happened to resolve.
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    # Nothing. This job runs commands the pull request declared.
    permissions: {}
    steps:
      - uses: actions/checkout@v4
        with:
          # The merge base is what a card diff is taken from, and a shallow
          # checkout has none. \`changedPaths\` reports that as "cannot answer"
          # rather than as an empty diff, so a shallow clone here would fail the
          # job rather than silently verify nothing — but it would still fail.
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: "${node}"
      # Values arrive through \`env:\`, never interpolated into the script. A
      # \`\${{ }}\` inside a \`run:\` block is expanded before the shell sees it, so a
      # branch name is code there; as an environment variable it is data.
      - name: Verify the cards this branch touched
        env:
          BASE_REF: \${{ github.base_ref }}
          HEAD_SHA: \${{ github.event.pull_request.head.sha }}
          RUN_URL: \${{ github.server_url }}/\${{ github.repository }}/actions/runs/\${{ github.run_id }}
        run: |
          npx --yes @illodev/workfile@${PACKAGE_VERSION} card verify --changed \\
            --base "origin/$BASE_REF" \\
            --close --run "$RUN_URL" --commit "$HEAD_SHA" \\
            --json > workfile-cards.json
      # Bounded to the protocol directory at the point it is produced, so the
      # job that applies it is not the only thing standing between a card
      # command and the rest of the repository.
      - name: Collect what the run wrote
        if: always()
        run: git diff -- ${protocolRoot} > workfile-cards.patch || true
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: workfile-cards
          path: |
            workfile-cards.json
            workfile-cards.patch
          if-no-files-found: ignore

  record:
    needs: cards
    # Same-repository pull requests only. A fork gets a read-only token whatever
    # this says, so the push there fails rather than being refused by us; this
    # condition keeps the job from starting in order to say so.
    if: >-
      github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      # The head branch, not the merge commit: a commit is being pushed to it.
      - uses: actions/checkout@v4
        with:
          ref: \${{ github.event.pull_request.head.ref }}
      - uses: actions/download-artifact@v4
        with:
          name: workfile-cards
      # This job runs no Workfile command, deliberately. Every one of them
      # \`import()\`s project.config.mjs from the checkout, which is the code this
      # job exists not to execute while holding a write token.
      - name: Refuse a patch that reaches outside the protocol directory
        run: |
          test -s workfile-cards.patch || exit 0
          git apply --check workfile-cards.patch
          if git apply --numstat workfile-cards.patch | cut -f3 |
              grep -qv '^${protocolRoot}/'; then
            echo "::error::refusing a patch that reaches outside ${protocolRoot}/"
            exit 1
          fi
      # No loop, for two independent reasons and the first one is the load
      # bearing one: a push made with GITHUB_TOKEN does not start a workflow
      # run, so this does not re-enter. Observed as a run created in
      # \`action_required\` that never executes. And if it did run, it would find
      # the cards already recorded, produce an empty patch and commit nothing —
      # which is what makes the first reason safe to rely on rather than
      # load-bearing on its own.
      - name: Commit the evidence
        run: |
          test -s workfile-cards.patch || exit 0
          git apply workfile-cards.patch
          git add -- ${protocolRoot}
          git diff --cached --quiet && exit 0
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Record card verification from CI"
          git push
`;
}

function gitlabBody(workspace) {
    const node = String(workspace.config.ci.nodeVersion || "22");
    return `# Generated by @illodev/workfile ${PACKAGE_VERSION}
#
${executesRepositoryCode()}
#
# GitLab has no per-job permission scope. This job sees every CI/CD variable
# that is not marked protected, and the branch rule below fires on any branch
# push, so anyone who can push a branch gets them — mark the variables
# protected, or keep the secrets out of this project. CI_JOB_TOKEN is always
# present and reaches whatever the job-token allowlist permits.
#
# This file does nothing on its own: GitLab reads .gitlab-ci.yml, so add
# \`include: { local: .gitlab/workfile.yml }\` there or no pipeline runs.
#
# It also does not run the commands cards declare, and that is the same fact read
# once more. On GitHub those run in a job holding \`permissions: {}\`, with a
# second job doing the write — see T-0189. There is no scope to put them behind
# here: this job sees every unprotected variable in the project, so running a
# command a merge request declared would run it beside the credentials. Enabling
# it is a decision only the maintainer can make, and it needs the variables
# protected or absent first:
#
#   - npx --yes @illodev/workfile@${PACKAGE_VERSION} card verify --changed
#       --base "origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
#
# Without \`--close\` it reports and writes nothing back, which is the half that
# needs no token at all.
project_protocol:
  image: node:${node}-slim
  stage: test
  interruptible: true
  timeout: 10m
  script:
    - npx --yes @illodev/workfile@${PACKAGE_VERSION} doctor --json
    - npx --yes @illodev/workfile@${PACKAGE_VERSION} agents check --json
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH
`;
}

function genericBody() {
    return `#!/usr/bin/env sh
# Generated by @illodev/workfile ${PACKAGE_VERSION}
#
${executesRepositoryCode()}
#
# There is no permission model to configure here: this script inherits the
# entire environment of whatever invokes it — a credential block on a build
# agent, a developer's ~/.npmrc and ssh-agent, an instance metadata endpoint.
# Workfile controls none of it, so "run repository checks where there are no
# secrets" is something the caller has to arrange and this file can only state.
#
# Which is also why it does not run the commands cards declare. On GitHub those
# get a job that holds nothing and a separate one that writes — T-0189. Here
# there is nothing to hold them behind, so \`card verify --changed --base REF\`
# is left for a caller who knows what this script inherits.
set -eu

npx --yes @illodev/workfile@${PACKAGE_VERSION} doctor --json
npx --yes @illodev/workfile@${PACKAGE_VERSION} agents check --json
`;
}

function targetBody(workspace, id) {
    if (id === "github") return githubBody(workspace);
    if (id === "gitlab") return gitlabBody(workspace);
    if (id === "generic") return genericBody();
    throw new ValidationError(
        "CI_TARGET_UNSUPPORTED",
        `Unsupported CI target: ${id}`,
        { target: id, supported: Object.keys(CI_TARGETS) }
    );
}

/**
 * The files `syncCiTemplates` writes, named without a workspace, so `init` can
 * count them before the workspace exists. See `agentArtifactPaths`.
 */
export function ciArtifactPaths(root, config, selectedTargets?) {
    return (selectedTargets || config.ci.targets)
        .filter((id) => CI_TARGETS[id])
        .map((id) => resolve(root, CI_TARGETS[id].path));
}

export function renderCiFiles(workspace, options: any = {}) {
    const targets = options.targets || workspace.config.ci.targets;
    return targets.map((id) => {
        const definition = CI_TARGETS[id];
        if (!definition) {
            throw new ValidationError(
                "CI_TARGET_UNSUPPORTED",
                `Unsupported CI target: ${id}`,
                { target: id, supported: Object.keys(CI_TARGETS) }
            );
        }
        return {
            id,
            path: resolve(workspace.root, definition.path),
            label: definition.path,
            requireMarker: true,
            block: renderManagedBlock({
                kind: definition.kind,
                version: PACKAGE_VERSION,
                body: targetBody(workspace, id),
                style: "hash"
            })
        };
    });
}

export async function syncCiTemplates(workspace, options: any = {}) {
    if (!options.dryRun) ensureWritable(workspace);
    const files = renderCiFiles(workspace, options);
    const results = [];
    for (const file of files) {
        const result = await syncManagedFile({
            ...file,
            force: Boolean(options.force),
            dryRun: Boolean(options.dryRun)
        });
        if (!options.dryRun && file.id === "generic") {
            await chmod(file.path, 0o755);
        }
        results.push(result);
    }
    return {
        version: PACKAGE_VERSION,
        targets: options.targets || workspace.config.ci.targets,
        changed: results.filter((item) => item.status !== "unchanged").length,
        files: results
    };
}

export async function checkCiTemplates(workspace, options: any = {}) {
    const files = renderCiFiles(workspace, options);
    const results: ManagedFileReport[] = [];
    for (const file of files) {
        results.push(
            await inspectManagedFile({
                path: file.path,
                block: file.block,
                label: file.label
            })
        );
    }
    const issues = results
        .filter((item) => item.status !== "current")
        .map((item) => ({
            severity: "warning",
            code:
                item.status === "missing"
                    ? "ci-template-missing"
                    : item.status === "unmanaged"
                      ? "ci-template-unmanaged"
                      : "ci-template-stale",
            file: item.path,
            message:
                item.status === "missing"
                    ? `Generated CI template is missing: ${item.path}`
                    : item.status === "unmanaged"
                      ? `Generated CI template has no managed block: ${item.path}`
                      : `Generated CI template is stale: ${item.path}${item.reason ? ` (${item.reason})` : ""}`,
            details: item
        }));
    return {
        ok: issues.length === 0,
        version: PACKAGE_VERSION,
        counts: {
            current: results.filter((item) => item.status === "current").length,
            stale: results.filter((item) => item.status === "stale").length,
            missing: results.filter((item) => item.status === "missing").length,
            unmanaged: results.filter((item) => item.status === "unmanaged").length
        },
        files: results,
        issues
    };
}
