import { chmod, readFile } from "node:fs/promises";
import { resolve } from "node:path";

import { ValidationError } from "../../core/errors.js";
import { ensureWritable } from "../../core/guards.js";
import {
    inspectManagedFile,
    type ManagedFileReport,
    renderManagedBlock,
    syncManagedFile
} from "../generated/managed-files.js";

const PACKAGE_VERSION = JSON.parse(
    await readFile(new URL("../../../../package.json", import.meta.url), "utf8")
).version;

export const CI_TARGETS = Object.freeze({
    github: {
        path: ".github/workflows/workfile.yml",
        kind: "ci-github",
        mode: "dedicated"
    },
    gitlab: {
        path: ".gitlab/workfile.yml",
        kind: "ci-gitlab",
        mode: "dedicated"
    },
    generic: {
        path: ".project/ci/workfile.sh",
        kind: "ci-generic",
        mode: "dedicated"
    }
});

/**
 * The job runs the checkout's own code, and the template says so.
 *
 * Every command below loads the workspace, and loading a workspace `import()`s
 * `project.config.mjs` out of the checkout — so on a pull request this job
 * executes code the pull request wrote, before it reads a single card. That is
 * the ordinary cost of building a pull request rather than a defect, and it is
 * why the useful controls here are about what the job *holds* rather than about
 * what it runs. The three targets differ sharply on that, and each says what it
 * can enforce and what it cannot.
 */
function githubBody(workspace) {
    const node = String(workspace.config.ci.nodeVersion || "22");
    return `# Generated by @illodev/workfile ${PACKAGE_VERSION}
name: Workfile

on:
  pull_request:
  push:
    branches: [main, master, dev]

# Nothing at the top level, so a job added by hand starts from no permissions
# rather than inheriting these. This job runs code from the checkout, including
# a fork's on \`pull_request\`; what protects the repository there is GitHub
# withholding secrets from a fork, not the scope below.
permissions: {}

jobs:
  doctor:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          # Otherwise the token is left in .git/config as an http.extraheader,
          # where any later step can read it. Nothing here pushes.
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: "${node}"
      - name: Validate repository protocol
        run: npx --yes @illodev/workfile@${PACKAGE_VERSION} doctor --json
      - name: Check generated agent instructions
        run: npx --yes @illodev/workfile@${PACKAGE_VERSION} agents check --json
`;
}

function gitlabBody(workspace) {
    const node = String(workspace.config.ci.nodeVersion || "22");
    return `# Generated by @illodev/workfile ${PACKAGE_VERSION}
#
# GitLab has no per-job permission scope. This job sees every CI/CD variable
# that is not marked protected, and the branch rule below fires on any branch
# push, so anyone who can push a branch gets them — mark the variables
# protected, or keep the secrets out of this project. CI_JOB_TOKEN is always
# present and reaches whatever the job-token allowlist permits.
#
# This file does nothing on its own: GitLab reads .gitlab-ci.yml, so add
# \`include: { local: .gitlab/workfile.yml }\` there or no pipeline runs.
project_protocol:
  image: node:${node}-slim
  stage: test
  interruptible: true
  timeout: 10m
  script:
    - npx --yes @illodev/workfile@${PACKAGE_VERSION} doctor --json
    - npx --yes @illodev/workfile@${PACKAGE_VERSION} agents check --json
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH
`;
}

function genericBody() {
    return `#!/usr/bin/env sh
# Generated by @illodev/workfile ${PACKAGE_VERSION}
#
# There is no permission model to configure here: this script inherits the
# entire environment of whatever invokes it — a credential block on a build
# agent, a developer's ~/.npmrc and ssh-agent, an instance metadata endpoint.
# Workfile controls none of it, so "run repository checks where there are no
# secrets" is something the caller has to arrange and this file can only state.
set -eu

npx --yes @illodev/workfile@${PACKAGE_VERSION} doctor --json
npx --yes @illodev/workfile@${PACKAGE_VERSION} agents check --json
`;
}

function targetBody(workspace, id) {
    if (id === "github") return githubBody(workspace);
    if (id === "gitlab") return gitlabBody(workspace);
    if (id === "generic") return genericBody();
    throw new ValidationError(
        "CI_TARGET_UNSUPPORTED",
        `Unsupported CI target: ${id}`,
        { target: id, supported: Object.keys(CI_TARGETS) }
    );
}

/**
 * The files `syncCiTemplates` writes, named without a workspace, so `init` can
 * count them before the workspace exists. See `agentArtifactPaths`.
 */
export function ciArtifactPaths(root, config, selectedTargets?) {
    return (selectedTargets || config.ci.targets)
        .filter((id) => CI_TARGETS[id])
        .map((id) => resolve(root, CI_TARGETS[id].path));
}

export function renderCiFiles(workspace, options: any = {}) {
    const targets = options.targets || workspace.config.ci.targets;
    return targets.map((id) => {
        const definition = CI_TARGETS[id];
        if (!definition) {
            throw new ValidationError(
                "CI_TARGET_UNSUPPORTED",
                `Unsupported CI target: ${id}`,
                { target: id, supported: Object.keys(CI_TARGETS) }
            );
        }
        return {
            id,
            path: resolve(workspace.root, definition.path),
            label: definition.path,
            requireMarker: true,
            block: renderManagedBlock({
                kind: definition.kind,
                version: PACKAGE_VERSION,
                body: targetBody(workspace, id),
                style: "hash"
            })
        };
    });
}

export async function syncCiTemplates(workspace, options: any = {}) {
    if (!options.dryRun) ensureWritable(workspace);
    const files = renderCiFiles(workspace, options);
    const results = [];
    for (const file of files) {
        const result = await syncManagedFile({
            ...file,
            force: Boolean(options.force),
            dryRun: Boolean(options.dryRun)
        });
        if (!options.dryRun && file.id === "generic") {
            await chmod(file.path, 0o755);
        }
        results.push(result);
    }
    return {
        version: PACKAGE_VERSION,
        targets: options.targets || workspace.config.ci.targets,
        changed: results.filter((item) => item.status !== "unchanged").length,
        files: results
    };
}

export async function checkCiTemplates(workspace, options: any = {}) {
    const files = renderCiFiles(workspace, options);
    const results: ManagedFileReport[] = [];
    for (const file of files) {
        results.push(
            await inspectManagedFile({
                path: file.path,
                block: file.block,
                label: file.label
            })
        );
    }
    const issues = results
        .filter((item) => item.status !== "current")
        .map((item) => ({
            severity: "warning",
            code:
                item.status === "missing"
                    ? "ci-template-missing"
                    : item.status === "unmanaged"
                      ? "ci-template-unmanaged"
                      : "ci-template-stale",
            file: item.path,
            message:
                item.status === "missing"
                    ? `Generated CI template is missing: ${item.path}`
                    : item.status === "unmanaged"
                      ? `Generated CI template has no managed block: ${item.path}`
                      : `Generated CI template is stale: ${item.path}${item.reason ? ` (${item.reason})` : ""}`,
            details: item
        }));
    return {
        ok: issues.length === 0,
        version: PACKAGE_VERSION,
        counts: {
            current: results.filter((item) => item.status === "current").length,
            stale: results.filter((item) => item.status === "stale").length,
            missing: results.filter((item) => item.status === "missing").length,
            unmanaged: results.filter((item) => item.status === "unmanaged").length
        },
        files: results,
        issues
    };
}
